CREATE TABLE IF NOT EXISTS orders (
    id SERIAL PRIMARY KEY,
    customer_name VARCHAR(100),
    product VARCHAR(100),
    quantity INT DEFAULT 0 NOT NULL,
    price NUMERIC(10,2) DEFAULT 0 NOT NULL,
    order_date TIMESTAMP,
    status VARCHAR(50)
);


ALTER TABLE orders
ADD COLUMN IF NOT EXISTS price NUMERIC(10,2) DEFAULT 0 NOT NULL;

ALTER TABLE orders
ADD COLUMN IF NOT EXISTS quantity INT DEFAULT 0 NOT NULL;

